CREATE DATABASE IF NOT EXISTS sequelize_store;

CREATE TABLE products(
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
  	name VARCHAR(255) NOT NULL,
  	price DECIMAL(15,2) NOT NULL,
  	quantity INTEGER NOT NULL,
  	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE producers(
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
  	name VARCHAR(255) NOT NULL,
  	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE products ADD COLUMN id_producer INTEGER AFTER quantity;

ALTER TABLE products ADD CONSTRAINT id_fk_producers
FOREIGN KEY(id_producer) REFERENCES producers(id);

CREATE TABLE categories(
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
  	name VARCHAR(255) NOT NULL,
  	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products_categories(
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
  	id_product INTEGER,
  	id_category INTEGER,
  	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  	CONSTRAINT id_fk_products FOREIGN KEY (id_product) REFERENCES products(id),
  	CONSTRAINT id_fk_categories FOREIGN KEY (id_category) REFERENCES categories(id)
);